create table if not exists company_directory_official_facts (
  profile_id uuid primary key references company_directory_profiles(id) on delete cascade,
  registration_country_code text not null default '',
  registration_country_label text not null default '',
  organization_form_code text not null default '',
  organization_form_label text not null default '',
  legal_form_code text not null default '',
  legal_form_label text not null default '',
  registration_date date,
  scb_registered_date date,
  deregistration_date timestamptz,
  deregistration_reason_code text not null default '',
  deregistration_reason_label text not null default '',
  advertising_blocked boolean,
  co_address text not null default '',
  address_country text not null default '',
  registered_names jsonb not null default '[]'::jsonb,
  sni_codes jsonb not null default '[]'::jsonb,
  ongoing_procedures jsonb not null default '[]'::jsonb,
  data_producers jsonb not null default '{}'::jsonb,
  source_payload_hash text not null default '',
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
