const additionalAreaDefinitions = [
  { slug: "hammersmith", name: "Hammersmith", region: "Greater London" },
  { slug: "chiswick", name: "Chiswick", region: "Greater London" },
  { slug: "brentford", name: "Brentford", region: "Greater London" },
  { slug: "isleworth", name: "Isleworth", region: "Greater London" },
  { slug: "twickenham", name: "Twickenham", region: "Greater London" },
  { slug: "richmond", name: "Richmond", region: "Greater London" },
  { slug: "kensington", name: "Kensington", region: "Greater London" },
  { slug: "hounslow", name: "Hounslow", region: "Greater London" },
  { slug: "west-ealing", name: "West Ealing", region: "Greater London" },
  { slug: "south-ealing", name: "South Ealing", region: "Greater London" },
  { slug: "hanwell", name: "Hanwell", region: "Greater London" },
  { slug: "perivale", name: "Perivale", region: "Greater London" },
  { slug: "southall", name: "Southall", region: "Greater London" },
  { slug: "hayes", name: "Hayes", region: "Greater London" },
  { slug: "northwood", name: "Northwood", region: "Greater London" },
  { slug: "west-drayton", name: "West Drayton", region: "Greater London" },
  { slug: "feltham", name: "Feltham", region: "Greater London" },
  { slug: "hampton", name: "Hampton", region: "Greater London" },
  { slug: "hampton-hill", name: "Hampton Hill", region: "Greater London" },
  { slug: "teddington", name: "Teddington", region: "Greater London" },
  { slug: "whitton", name: "Whitton", region: "Greater London" },
  { slug: "osterley", name: "Osterley", region: "Greater London" },
  { slug: "shepherds-bush", name: "Shepherd’s Bush", region: "Greater London" },
  { slug: "white-city", name: "White City", region: "Greater London" },
  { slug: "west-kensington", name: "West Kensington", region: "Greater London" },
  { slug: "earls-court", name: "Earls Court", region: "Greater London" },
  { slug: "fulham", name: "Fulham", region: "Greater London" },
  { slug: "putney", name: "Putney", region: "Greater London" },
  { slug: "barnes", name: "Barnes", region: "Greater London" },
  { slug: "mortlake", name: "Mortlake", region: "Greater London" },
  { slug: "east-sheen", name: "East Sheen", region: "Greater London" },
  { slug: "kew", name: "Kew", region: "Greater London" },
  { slug: "kingston-upon-thames", name: "Kingston upon Thames", region: "Greater London" },
  { slug: "surbiton", name: "Surbiton", region: "Greater London" },
  { slug: "new-malden", name: "New Malden", region: "Greater London" },
  { slug: "wimbledon", name: "Wimbledon", region: "Greater London" },
  { slug: "raynes-park", name: "Raynes Park", region: "Greater London" },
  { slug: "epsom", name: "Epsom", region: "Surrey" },
  { slug: "camden", name: "Camden", region: "Greater London" },
  { slug: "kentish-town", name: "Kentish Town", region: "Greater London" },
  { slug: "hampstead", name: "Hampstead", region: "Greater London" },
  { slug: "highgate", name: "Highgate", region: "Greater London" },
  { slug: "archway", name: "Archway", region: "Greater London" },
  { slug: "holloway", name: "Holloway", region: "Greater London" },
  { slug: "finsbury-park", name: "Finsbury Park", region: "Greater London" },
  { slug: "crouch-end", name: "Crouch End", region: "Greater London" },
  { slug: "muswell-hill", name: "Muswell Hill", region: "Greater London" },
  { slug: "hornsey", name: "Hornsey", region: "Greater London" },
  { slug: "islington", name: "Islington", region: "Greater London" },
  { slug: "stoke-newington", name: "Stoke Newington", region: "Greater London" },
  { slug: "highbury", name: "Highbury", region: "Greater London" },
  { slug: "canonbury", name: "Canonbury", region: "Greater London" },
  { slug: "finchley", name: "Finchley", region: "Greater London" },
  { slug: "east-finchley", name: "East Finchley", region: "Greater London" },
  { slug: "north-finchley", name: "North Finchley", region: "Greater London" },
  { slug: "friern-barnet", name: "Friern Barnet", region: "Greater London" },
  { slug: "barnet", name: "Barnet", region: "Greater London" },
  { slug: "hendon", name: "Hendon", region: "Greater London" },
  { slug: "mill-hill", name: "Mill Hill", region: "Greater London" },
  { slug: "colindale", name: "Colindale", region: "Greater London" },
  { slug: "golders-green", name: "Golders Green", region: "Greater London" },
  { slug: "cricklewood", name: "Cricklewood", region: "Greater London" },
  { slug: "kilburn", name: "Kilburn", region: "Greater London" },
  { slug: "willesden", name: "Willesden", region: "Greater London" },
  { slug: "neasden", name: "Neasden", region: "Greater London" },
  { slug: "dollis-hill", name: "Dollis Hill", region: "Greater London" },
  { slug: "brent-cross", name: "Brent Cross", region: "Greater London" },
  { slug: "totteridge", name: "Totteridge", region: "Greater London" },
  { slug: "enfield", name: "Enfield", region: "Greater London" },
  { slug: "edmonton", name: "Edmonton", region: "Greater London" },
  { slug: "palmers-green", name: "Palmers Green", region: "Greater London" },
  { slug: "southgate", name: "Southgate", region: "Greater London" },
  { slug: "wood-green", name: "Wood Green", region: "Greater London" },
  { slug: "tottenham", name: "Tottenham", region: "Greater London" },
  { slug: "seven-sisters", name: "Seven Sisters", region: "Greater London" },
  { slug: "turnpike-lane", name: "Turnpike Lane", region: "Greater London" },
  { slug: "bounds-green", name: "Bounds Green", region: "Greater London" },
  { slug: "arnos-grove", name: "Arnos Grove", region: "Greater London" },
] as const;

export const primeViewAdditionalAreaPages = additionalAreaDefinitions.map(({ slug, name, region }) => ({
  slug,
  name,
  region,
  description: `Professional window, gutter and exterior cleaning in ${name} from PrimeView Window Care. Book online or request a free quote.`,
  intro: `PrimeView provides window and exterior cleaning in ${name} for homes and suitable business premises. Send your postcode, property details and service requirements and we will confirm the practical next step.`,
  bullets: [
    "Residential and commercial window cleaning",
    "Gutter and downpipe clearing",
    "Fascia, soffit and conservatory cleaning",
    "Pressure washing and solar panel cleaning",
  ],
  faq: [
    [`Does PrimeView cover ${name}?`, `Yes. ${name} is included in PrimeView's service area, subject to scheduling, property access and safe working conditions.`],
    ["Can I combine more than one cleaning service?", "Yes. Tell us which services you need and PrimeView can review them together for the same property."],
    [`How do I book in ${name}?`, "Use the online booking form and enter your postcode, property details and preferred visit time."],
  ],
}));
