export const primeViewServicePages = [
  { slug: "window-cleaning", name: "Window Cleaning", title: "Professional Window Cleaning in West & North London", description: "Reliable, streak-free window cleaning for homes, shops and businesses across West and North London.", intro: "PrimeView Window Care provides careful, professional window cleaning for residential and commercial properties across West and North London.", bullets: ["Frames, sills and glass cleaned with care", "One-off and regular visits available", "Homes, shops and business premises", "Free, no-obligation quotes"], faq: [["How often should windows be cleaned?", "Most homes benefit from cleaning every 4 to 8 weeks, depending on location and exposure."], ["Do I need to be home?", "Not always. If access is arranged in advance, exterior work can often be completed while you are away."], ["Do you clean commercial properties?", "Yes. We clean windows for shops, offices and other business premises."]] },
  { slug: "gutter-cleaning", name: "Gutter Cleaning", title: "Gutter Cleaning in West & North London", description: "Professional gutter and downpipe clearing to help prevent overflow, damp and avoidable property damage.", intro: "Blocked gutters can overflow and cause avoidable damage. PrimeView clears gutters and downpipes safely and thoroughly.", bullets: ["Removal of leaves, moss and debris", "Downpipe flow checks", "Homes and small commercial properties", "Clear quote before work begins"], faq: [["How often should gutters be cleaned?", "For most properties, once or twice per year is sensible, especially after autumn."], ["Can you clear downpipes?", "Yes. Downpipes are checked and cleared where accessible."], ["Why is gutter cleaning important?", "It helps reduce overflow, staining, damp risk and water damage around the property."]] },
  { slug: "solar-panel-cleaning", name: "Solar Panel Cleaning", title: "Solar Panel Cleaning in West & North London", description: "Safe, specialist solar panel cleaning for homes and businesses across West and North London.", intro: "Dust, bird mess and airborne dirt can reduce the amount of light reaching solar panels. PrimeView cleans panels with suitable equipment and careful methods.", bullets: ["Non-abrasive cleaning approach", "Residential and commercial panels", "Careful access assessment", "Free quotation"], faq: [["How often should solar panels be cleaned?", "Many properties benefit from an annual clean, depending on trees, birds, traffic and roof angle."], ["Do you use harsh chemicals?", "No. The cleaning method is selected to protect the panel surface."], ["Can cleaning improve performance?", "Removing visible dirt can help panels receive more light, though output also depends on weather and system condition."]] },
  { slug: "conservatory-cleaning", name: "Conservatory Cleaning", title: "Conservatory Roof Cleaning in West & North London", description: "Professional conservatory roof, glass and frame cleaning to restore clarity and improve appearance.", intro: "PrimeView cleans conservatory roofs, glass, frames and surrounding exterior surfaces to bring back a brighter, cleaner finish.", bullets: ["Roof panels and exterior glass", "Frames, trims and reachable gutters", "Careful treatment of algae and dirt", "Flexible appointment times"], faq: [["Do you clean polycarbonate roofs?", "Yes, subject to inspection and safe access."], ["Will you clean the frames too?", "Frames and reachable surrounding trims can be included in the quote."], ["How long does it take?", "Timing depends on size, access and the level of build-up."]] },
  { slug: "fascia-soffit-cleaning", name: "Fascia & Soffit Cleaning", title: "Fascia & Soffit Cleaning in West & North London", description: "Exterior fascia, soffit, cladding and trim cleaning for homes across West and North London.", intro: "Weather, traffic film and algae can leave roofline surfaces looking tired. PrimeView restores a cleaner, brighter finish.", bullets: ["Fascias, soffits and exterior trims", "Cladding where accessible", "Routine maintenance or property refreshes", "Combined service options available"], faq: [["Can this be combined with window cleaning?", "Yes. Combining services can be more convenient and cost-effective."], ["Do you clean upper-storey fascias?", "Yes, where safe access and suitable equipment allow."], ["Will all staining come off?", "Most surface dirt and organic build-up can be improved, though permanent discoloration may remain."]] },
  { slug: "driveway-patio-cleaning", name: "Driveway & Patio Cleaning", title: "Driveway & Patio Pressure Cleaning in West & North London", description: "Professional pressure cleaning for driveways, patios, paths and outdoor hard surfaces.", intro: "PrimeView pressure cleans driveways, patios and paths to remove built-up dirt and refresh outdoor spaces.", bullets: ["Driveways, patios and paths", "Dirt, algae and general surface build-up", "Residential and small commercial areas", "Assessment before pressure is applied"], faq: [["Which surfaces can be cleaned?", "Many concrete, block paving and stone surfaces can be cleaned, subject to inspection."], ["Will weeds return?", "Pressure cleaning removes visible growth, but future regrowth depends on conditions and maintenance."], ["Do you re-sand block paving?", "This can be discussed and included in the quotation where appropriate."]] },
] as const;

export const primeViewAreaPages = [
  { slug: "ealing", name: "Ealing", region: "West London" },
  { slug: "harrow", name: "Harrow", region: "North West London" },
  { slug: "wembley", name: "Wembley", region: "North West London" },
  { slug: "uxbridge", name: "Uxbridge", region: "West London" },
  { slug: "ruislip", name: "Ruislip", region: "West London" },
  { slug: "greenford", name: "Greenford", region: "West London" },
  { slug: "acton", name: "Acton", region: "West London" },
  { slug: "northolt", name: "Northolt", region: "West London" },
  { slug: "edgware", name: "Edgware", region: "North London" },
  { slug: "pinner", name: "Pinner", region: "North West London" },
] as const;
