export const primeViewServicePages = [
  {
    slug: "window-cleaning",
    name: "Window Cleaning",
    title: "Professional Window Cleaning in West & North London",
    description: "Reliable, streak-free window cleaning for homes, shops and businesses across West and North London.",
    intro: "PrimeView Window Care provides careful, professional window cleaning for residential and commercial properties across West and North London.",
    bullets: ["Frames, sills and glass cleaned with care", "One-off and regular visits available", "Homes, shops and business premises", "Free, no-obligation quotes"],
    faq: [["How often should windows be cleaned?", "Most homes benefit from cleaning every 4 to 8 weeks, depending on location and exposure."], ["Do I need to be home?", "Not always. If access is arranged in advance, exterior work can often be completed while you are away."], ["Do you clean commercial properties?", "Yes. We clean windows for shops, offices and other business premises."]],
  },
  {
    slug: "gutter-cleaning",
    name: "Gutter Cleaning",
    title: "Gutter Cleaning in West & North London",
    description: "Professional gutter and downpipe clearing to help prevent overflow, damp and avoidable property damage.",
    intro: "Blocked gutters can overflow and cause avoidable damage. PrimeView clears gutters and downpipes safely and thoroughly.",
    bullets: ["Removal of leaves, moss and debris", "Downpipe flow checks", "Homes and small commercial properties", "Clear quote before work begins"],
    faq: [["How often should gutters be cleaned?", "For most properties, once or twice per year is sensible, especially after autumn."], ["Can you clear downpipes?", "Yes. Downpipes are checked and cleared where accessible."], ["Why is gutter cleaning important?", "It helps reduce overflow, staining, damp risk and water damage around the property."]],
  },
  {
    slug: "solar-panel-cleaning",
    name: "Solar Panel Cleaning",
    title: "Solar Panel Cleaning in West & North London",
    description: "Safe, specialist solar panel cleaning for homes and businesses across West and North London.",
    intro: "Dust, bird mess and airborne dirt can reduce the amount of light reaching solar panels. PrimeView cleans panels with suitable equipment and careful methods.",
    bullets: ["Non-abrasive cleaning approach", "Residential and commercial panels", "Careful access assessment", "Free quotation"],
    faq: [["How often should solar panels be cleaned?", "Many properties benefit from an annual clean, depending on trees, birds, traffic and roof angle."], ["Do you use harsh chemicals?", "No. The cleaning method is selected to protect the panel surface."], ["Can cleaning improve performance?", "Removing visible dirt can help panels receive more light, though output also depends on weather and system condition."]],
  },
  {
    slug: "conservatory-cleaning",
    name: "Conservatory Cleaning",
    title: "Conservatory Roof Cleaning in West & North London",
    description: "Professional conservatory roof, glass and frame cleaning to restore clarity and improve appearance.",
    intro: "PrimeView cleans conservatory roofs, glass, frames and surrounding exterior surfaces to bring back a brighter, cleaner finish.",
    bullets: ["Roof panels and exterior glass", "Frames, trims and reachable gutters", "Careful treatment of algae and dirt", "Flexible appointment times"],
    faq: [["Do you clean polycarbonate roofs?", "Yes, subject to inspection and safe access."], ["Will you clean the frames too?", "Frames and reachable surrounding trims can be included in the quote."], ["How long does it take?", "Timing depends on size, access and the level of build-up."]],
  },
  {
    slug: "fascia-soffit-cleaning",
    name: "Fascia & Soffit Cleaning",
    title: "Fascia & Soffit Cleaning in West & North London",
    description: "Exterior fascia, soffit, cladding and trim cleaning for homes across West and North London.",
    intro: "Weather, traffic film and algae can leave roofline surfaces looking tired. PrimeView restores a cleaner, brighter finish.",
    bullets: ["Fascias, soffits and exterior trims", "Cladding where accessible", "Routine maintenance or property refreshes", "Combined service options available"],
    faq: [["Can this be combined with window cleaning?", "Yes. Combining services can be more convenient and cost-effective."], ["Do you clean upper-storey fascias?", "Yes, where safe access and suitable equipment allow."], ["Will all staining come off?", "Most surface dirt and organic build-up can be improved, though permanent discoloration may remain."]],
  },
  {
    slug: "driveway-patio-cleaning",
    name: "Driveway & Patio Cleaning",
    title: "Driveway & Patio Pressure Cleaning in West & North London",
    description: "Professional pressure cleaning for driveways, patios, paths and outdoor hard surfaces.",
    intro: "PrimeView pressure cleans driveways, patios and paths to remove built-up dirt and refresh outdoor spaces.",
    bullets: ["Driveways, patios and paths", "Dirt, algae and general surface build-up", "Residential and small commercial areas", "Assessment before pressure is applied"],
    faq: [["Which surfaces can be cleaned?", "Many concrete, block paving and stone surfaces can be cleaned, subject to inspection."], ["Will weeds return?", "Pressure cleaning removes visible growth, but future regrowth depends on conditions and maintenance."], ["Do you re-sand block paving?", "This can be discussed and included in the quotation where appropriate."]],
  },
] as const;

export const primeViewAreaPages = [
  {
    slug: "ealing",
    name: "Ealing",
    region: "West London",
    description: "Window cleaning, gutter cleaning and exterior cleaning in Ealing from PrimeView Window Care. Online booking and free quotes available.",
    intro: "PrimeView provides window and exterior cleaning across Ealing for homes, shops and business premises. Choose the service you need, send your property details and receive clear pricing before work begins.",
    bullets: ["Residential and commercial window cleaning", "Gutter and downpipe clearing", "Fascia, soffit and conservatory cleaning", "Pressure washing and solar panel cleaning"],
    faq: [["Do you provide window cleaning in Ealing?", "Yes. PrimeView serves Ealing for residential and commercial window cleaning, subject to availability and safe access."], ["Can I combine gutter and window cleaning?", "Yes. Tell us which services you need and we can prepare one clear quotation."], ["How do I book in Ealing?", "Use the online booking form or request a free quote with your postcode and property details."]],
  },
  {
    slug: "harrow",
    name: "Harrow",
    region: "North West London",
    description: "Professional window, gutter and exterior cleaning in Harrow for homes and businesses. Book online or request a free PrimeView quote.",
    intro: "PrimeView serves Harrow with practical exterior cleaning for residential and small commercial properties, from regular window cleaning to gutter, fascia and pressure-washing work.",
    bullets: ["Window cleaning for homes and businesses", "Gutter and downpipe cleaning", "Roofline and conservatory exterior cleaning", "Clear quotes before the visit"],
    faq: [["Does PrimeView cover Harrow?", "Yes. We take bookings across Harrow and nearby areas, subject to scheduling and access."], ["Can you clean upper-floor windows?", "Yes, where the working height and access can be handled safely with suitable equipment."], ["Can I get several exterior services in one visit?", "Yes. Add the services you need when requesting your quote or booking."]],
  },
  {
    slug: "wembley",
    name: "Wembley",
    region: "North West London",
    description: "Window and exterior cleaning in Wembley, including gutters, fascia, conservatories, solar panels and pressure washing.",
    intro: "For properties in Wembley, PrimeView offers window cleaning and a wider range of exterior-cleaning services with straightforward booking, clear communication and no-obligation quotations.",
    bullets: ["Window cleaning for houses, flats and premises", "Gutter clearing and roofline cleaning", "Patio and driveway pressure washing", "Solar panel and conservatory cleaning"],
    faq: [["Do you clean windows in Wembley?", "Yes. Window cleaning is available for suitable residential and commercial properties in Wembley."], ["Do you need parking at the property?", "Parking and access affect how the visit is planned, so the booking form asks you to tell us what is available."], ["How quickly can I get a quote?", "Send your postcode, service and property details and PrimeView will review the request and respond with the next steps."]],
  },
  {
    slug: "uxbridge",
    name: "Uxbridge",
    region: "West London",
    description: "Exterior cleaning in Uxbridge from PrimeView Window Care, including windows, gutters, fascia, patios and solar panels.",
    intro: "PrimeView helps households and businesses in Uxbridge keep exterior surfaces clean with window, gutter, fascia, conservatory, solar-panel and pressure-washing services.",
    bullets: ["Window cleaning with frames and sills", "Gutter and downpipe clearing", "Conservatory and roofline cleaning", "Outdoor hard-surface pressure washing"],
    faq: [["Can I book window cleaning in Uxbridge online?", "Yes. Use the PrimeView booking form and enter your postcode, property details and preferred visit time."], ["Do you offer one-off cleans?", "Yes. One-off work can be requested as well as repeat window-cleaning visits."], ["Can you quote from my property details?", "Yes. Provide accurate access, height, quantity and service information so we can review the job properly."]],
  },
  {
    slug: "ruislip",
    name: "Ruislip",
    region: "West London",
    description: "Window, gutter and exterior cleaning in Ruislip with online booking and clear quotes from PrimeView Window Care.",
    intro: "PrimeView provides exterior cleaning in Ruislip with a focus on careful work and simple communication. Window cleaning can be booked alongside gutter, fascia, conservatory and outdoor-surface cleaning.",
    bullets: ["Window cleaning for residential properties", "Gutter and downpipe cleaning", "Fascia, soffit and conservatory cleaning", "Free, no-obligation quotations"],
    faq: [["Does PrimeView work in Ruislip?", "Yes. Ruislip is within the areas we serve, subject to appointment availability."], ["Can gutters and fascias be cleaned together?", "Yes. These services can be requested together and quoted based on the property."], ["What information should I provide?", "Your postcode, property type, access details and the services required help us assess the job accurately."]],
  },
  {
    slug: "greenford",
    name: "Greenford",
    region: "West London",
    description: "Professional window and exterior cleaning in Greenford for homes and businesses, with free quotes from PrimeView Window Care.",
    intro: "PrimeView serves Greenford with window cleaning and exterior maintenance services designed for homes, shops and small business premises. Tell us what needs cleaning and we will confirm the practical next step.",
    bullets: ["Window cleaning for homes and premises", "Gutter clearing and downpipe checks", "Fascia, soffit and conservatory exterior cleaning", "Pressure washing for suitable hard surfaces"],
    faq: [["Do you provide commercial window cleaning in Greenford?", "Yes. Suitable shops, offices and other business premises can request a quote."], ["Can I send access notes before the visit?", "Yes. The booking form includes space for parking, access, pets and anything else the team should know."], ["Is a quote free?", "Yes. PrimeView offers free, no-obligation quotations."]],
  },
  {
    slug: "acton",
    name: "Acton",
    region: "West London",
    description: "Window cleaning and exterior cleaning in Acton from PrimeView, including gutters, fascia, conservatories and pressure washing.",
    intro: "PrimeView provides exterior cleaning throughout Acton for residential and commercial properties. Services range from routine window cleaning to gutter clearing, roofline cleaning and pressure washing.",
    bullets: ["Routine and one-off window cleaning", "Gutter and downpipe clearing", "Fascia, soffit and conservatory cleaning", "Driveway and patio pressure washing"],
    faq: [["Can I arrange regular window cleaning in Acton?", "Yes. Ask PrimeView about repeat visits when requesting your quote."], ["Do you clean flats and apartments?", "Suitable flats and apartments can be quoted where safe exterior access is available."], ["Can I book without calling?", "Yes. Use the online booking form to submit the job and verify your email."]],
  },
  {
    slug: "northolt",
    name: "Northolt",
    region: "West London",
    description: "Window, gutter and exterior cleaning in Northolt from PrimeView Window Care. Book online or request a free quote.",
    intro: "PrimeView offers window and exterior cleaning in Northolt with transparent service details and straightforward booking. We assess access and working height before confirming the work.",
    bullets: ["Window cleaning with clear starting prices", "Gutter and downpipe clearing", "Roofline and conservatory exterior cleaning", "Property-specific access assessment"],
    faq: [["Do you cover Northolt for window cleaning?", "Yes. Northolt is included in PrimeView's service area, subject to scheduling."], ["What if rear access is through the house?", "Tell us in the booking form. Access information is reviewed before the appointment is confirmed."], ["Can I request pressure washing too?", "Yes. Pressure washing can be requested for suitable patios, driveways and paths."]],
  },
  {
    slug: "edgware",
    name: "Edgware",
    region: "North London",
    description: "Window and exterior cleaning in Edgware, including gutters, fascia, conservatories, solar panels and pressure washing.",
    intro: "PrimeView serves Edgware with professional exterior cleaning for homes and businesses. We keep the process simple from postcode and property details through quotation and appointment confirmation.",
    bullets: ["Residential and commercial window cleaning", "Gutter and downpipe cleaning", "Fascia, soffit and conservatory work", "Solar panel and hard-surface cleaning"],
    faq: [["Does PrimeView provide window cleaning in Edgware?", "Yes. We serve suitable properties in Edgware and nearby North London areas."], ["Can I select a preferred date online?", "Yes. The booking form shows available times and lets you submit a preferred visit slot."], ["Will the appointment be confirmed immediately?", "PrimeView reviews the booking details and confirms the final appointment after the request is submitted."]],
  },
  {
    slug: "pinner",
    name: "Pinner",
    region: "North West London",
    description: "Professional window, gutter and exterior cleaning in Pinner with clear quotes and online booking from PrimeView Window Care.",
    intro: "PrimeView provides window and exterior cleaning in Pinner for homeowners and suitable commercial properties, with flexible service combinations and clear communication before the visit.",
    bullets: ["Window cleaning for homes and premises", "Gutter and roofline cleaning", "Conservatory and solar panel cleaning", "Driveway and patio pressure washing"],
    faq: [["Can I book PrimeView in Pinner?", "Yes. Enter your postcode and job details online to request a suitable appointment."], ["Can multiple services be quoted together?", "Yes. List everything you need cleaned so the work can be assessed together."], ["Do you provide free quotes?", "Yes. Quotations are free and there is no obligation to proceed."]],
  },
] as const;
