/* eslint-disable react-hooks/purity */
import Link from "next/link";
import { revalidatePath } from "next/cache";
import { notFound } from "next/navigation";
import { CalendarClock, CalendarDays, Clock3, History, MapPin, XCircle } from "lucide-react";
import { cancelCustomerCalendarBooking, getCustomerCalendar, type CustomerCalendarBooking } from "@/lib/customer-calendar";
import type { WorkspaceTimeZone } from "@/lib/workspace-market";

export const dynamic = "force-dynamic";
type PageProps = { params: Promise<{ token: string }>; searchParams?: Promise<{ changed?: string; cancelled?: string; error?: string }> };
const statusLabels: Record<string,string>={draft:"Utkast",requested:"Förfrågad",confirmed:"Bekräftad",completed:"Genomförd",cancelled:"Avbokad",no_show:"Uteblev"};
const formatDate=(v:string,tz:WorkspaceTimeZone)=>new Intl.DateTimeFormat("sv-SE",{timeZone:tz,weekday:"short",day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v));
async function cancelBooking(formData:FormData){"use server";const token=String(formData.get("token")??"");const id=String(formData.get("booking_id")??"");const r=await cancelCustomerCalendarBooking(token,id);if(r.ok){revalidatePath(`/mina-bokningar/${token}`);return;} }
function BookingCard({booking,token,timeZone,canReschedule,canCancel,cancelNoticeHours}:{booking:CustomerCalendarBooking;token:string;timeZone:WorkspaceTimeZone;canReschedule:boolean;canCancel:boolean;cancelNoticeHours:number}){
 const calendarUrl=`/api/mina-bokningar/${encodeURIComponent(token)}/${encodeURIComponent(booking.id)}/calendar`;
 const start=new Date(booking.startsAt).getTime(),isPast=start<=Date.now(),active=["requested","confirmed"].includes(booking.status)&&!isPast;
 const rescheduleAllowed=active&&canReschedule;const cancelAllowed=active&&canCancel&&start>Date.now()+cancelNoticeHours*3600000;
 const displayStatus=isPast&&["requested","confirmed"].includes(booking.status)?"Tiden har passerat":statusLabels[booking.status]??booking.status;
 return <article className="rounded-2xl border border-[#dfe6df] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#647269]">{displayStatus}</p><h3 className="mt-1 text-lg font-bold text-[#17201a]">{booking.title}</h3><p className="mt-1 text-sm text-[#5c685f]">{booking.service}</p></div><span className="rounded-full bg-[#edf5ef] px-3 py-1 text-xs font-bold text-[#17452f]">Privat bokning</span></div><div className="mt-4 grid gap-2 text-sm text-[#344139]"><p className="flex items-center gap-2"><Clock3 className="h-4 w-4" />{formatDate(booking.startsAt,timeZone)}</p>{booking.city?<p className="flex items-center gap-2"><MapPin className="h-4 w-4" />{booking.city}</p>:null}</div><div className="mt-5 flex flex-wrap gap-2"><Link href={calendarUrl} className="inline-flex min-h-10 items-center rounded-xl border border-[#cfd9d0] px-4 py-2 text-sm font-bold text-[#17452f]">Lägg till i kalender</Link>{rescheduleAllowed?<Link href={`/mina-bokningar/${encodeURIComponent(token)}/${booking.id}/boka-om`} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[#b8d3c0] px-4 py-2 text-sm font-bold text-[#17452f]"><CalendarClock className="h-4 w-4" />Boka om</Link>:null}{cancelAllowed?<form action={cancelBooking}><input type="hidden" name="token" value={token}/><input type="hidden" name="booking_id" value={booking.id}/><button type="submit" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[#efc8c3] px-4 py-2 text-sm font-bold text-[#a5362a]"><XCircle className="h-4 w-4"/>Avboka</button></form>:null}</div>{active&&!rescheduleAllowed&&!cancelAllowed?<p className="mt-3 text-xs text-[#6c756f]">Företaget har stängt av självservice för den här bokningen.</p>:null}{active&&canCancel&&!cancelAllowed?<p className="mt-3 text-xs text-[#6c756f]">Avbokning online stänger {cancelNoticeHours} timmar före start.</p>:null}{isPast&&["requested","confirmed"].includes(booking.status)?<p className="mt-3 text-xs text-[#6c756f]">Bokningstiden har passerat. Företaget kan markera den som genomförd eller utebliven.</p>:null}</article>;
}
export default async function Page({params,searchParams}:PageProps){const{token}=await params;const query=searchParams?await searchParams:undefined;const data=await getCustomerCalendar(token);if(!data)notFound();const card=(b:CustomerCalendarBooking)=><BookingCard key={b.id} booking={b} token={token} timeZone={data.timeZone} canReschedule={data.policy.customerRescheduleEnabled} canCancel={data.policy.customerCancelEnabled} cancelNoticeHours={data.policy.cancelNoticeHours}/>;return <main className="min-h-screen bg-[#f4f7f3] px-4 py-8 sm:px-6"><div className="mx-auto grid max-w-4xl gap-6"><header className="rounded-[28px] bg-[#173e2b] p-6 text-white shadow-sm sm:p-8"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/12"><CalendarDays className="h-5 w-5"/></span><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-white/70">Mina bokningar</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Hej {data.customer.name}</h1></div></div><p className="mt-4 max-w-2xl text-sm leading-7 text-white/80">Här visas endast dina egna bokningar. Tillgängliga åtgärder styrs av företagets bokningsregler.</p></header>{query?.changed==="1"?<p className="rounded-xl bg-[#eaf6ed] p-4 text-sm font-bold text-[#17452f]">Tiden har ändrats.</p>:null}<section className="rounded-[24px] border border-[#dfe6df] bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-[#17452f]"/><h2 className="text-xl font-bold">Kommande</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{data.upcoming.length?data.upcoming.map(card):<p className="text-sm text-[#667168]">Du har inga kommande bokningar.</p>}</div></section><section className="rounded-[24px] border border-[#dfe6df] bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><History className="h-5 w-5 text-[#17452f]"/><h2 className="text-xl font-bold">Historik</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{data.history.length?data.history.map(card):<p className="text-sm text-[#667168]">Ingen bokningshistorik ännu.</p>}</div></section></div></main>}