import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { getWorkspaceMemberInvitation } from "@/features/company/workspace-member-invitation";
import { ActivationForm } from "@/app/aktivera/[token]/activation-form";
import { acceptMemberInvitationAction } from "./actions";
export const metadata:Metadata={title:"Gå med i arbetsyta",robots:{index:false,follow:false}};
const messages:Record<string,string>={password:"Lösenorden måste vara lika och innehålla minst 8 tecken.",expired:"Länken har gått ut. Be Owner skicka en ny inbjudan.",account:"Kontot kunde inte skapas. Kontakta den som bjöd in dig.",database:"Inbjudan kunde inte slutföras just nu.",invalid:"Länken är ogiltig eller redan använd."};
export default async function MemberInvitePage({params,searchParams}:{params:Promise<{token:string}>;searchParams?:Promise<{error?:string|string[]}>}){const [{token},query]=await Promise.all([params,searchParams??Promise.resolve(undefined)]);const invite=await getWorkspaceMemberInvitation(token),error=Array.isArray(query?.error)?query?.error[0]:query?.error;if(!invite)return <main className="min-h-screen bg-[#f7f7f4] px-4 py-16"><section className="mx-auto max-w-xl rounded-3xl bg-white p-8 text-center shadow-sm ring-1 ring-[#dfe5dd]"><h1 className="text-3xl font-bold text-[#17201a]">Länken kan inte användas</h1><p className="mt-4 text-[#5b665f]">Den är ogiltig, har gått ut eller har redan använts.</p><Link href="/kontakt" className="mt-7 inline-flex min-h-11 items-center rounded-xl bg-[#17452f] px-5 text-sm font-bold text-white">Kontakta Proffera</Link></section></main>;const action=acceptMemberInvitationAction.bind(null,token);return <main className="min-h-screen bg-[#f7f7f4] px-4 py-10 sm:py-16"><div className="mx-auto grid max-w-4xl overflow-hidden rounded-[1.75rem] bg-white shadow-sm ring-1 ring-[#dfe5dd] lg:grid-cols-[0.85fr_1.15fr]"><section className="bg-[#102a1c] p-7 text-white sm:p-10"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#a9dbb9]">Proffera kundportal</p><h1 className="mt-4 text-3xl font-bold">Du är inbjuden till {invite.companyName}</h1><ul className="mt-8 space-y-4 text-sm text-white/85"><li className="flex gap-3"><CheckCircle2 className="h-5 w-5 text-[#a9dbb9]" />Egen åtkomst till arbetsytan.</li><li className="flex gap-3"><ShieldCheck className="h-5 w-5 text-[#a9dbb9]" />Länken kan bara användas en gång.</li></ul></section><section className="p-6 sm:p-10"><h2 className="text-2xl font-bold text-[#17201a]">Skapa ditt konto</h2><p className="mt-3 text-sm text-[#5b665f]">Konto: <strong>{invite.email}</strong></p>{error?<p className="mt-5 rounded-xl bg-[#fff4f2] px-4 py-3 text-sm font-semibold text-[#8a2b20]">{messages[error]??messages.invalid}</p>:null}<ActivationForm action={action}/></section></div></main>;}
